### ISSUE TITLE
Restart Bot Crash

### ISSUE THREAD

**Issue by Thaliruth** [greatplainsmodding/DBM-Dashboard#18]
When I execute my restart command in Discord, or I crash the bot via the Dashbord Restarte Chrasht er. The commands in Dashbord still work, but on Discord the bot doesn't react anymore. This seems to be the problem that the Dashbord URL is already taken, which is logical somewhere.

`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/application.js:618:24)
    at module.exports (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/bin/express.js:89:19)
    at Object.DBM.Bot.onReady (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT.js:290:47)
    at Client.emit (events.js:327:22)
    at WebSocketConnection.triggerReady (/home/thaliruth/gollum/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/home/thaliruth/gollum/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/home/thaliruth/gollum/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
(node:23859) UnhandledPromiseRejectionWarning: Error: Command failed: node bot.js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/application.js:618:24)
    at module.exports (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/bin/express.js:89:19)
    at Object.DBM.Bot.onReady (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT.js:290:47)
    at Client.emit (events.js:327:22)
    at WebSocketConnection.triggerReady (/home/thaliruth/gollum/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/home/thaliruth/gollum/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/home/thaliruth/gollum/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.run (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/actions/actions/restart_bot_mod.js:108:15)
    at /home/thaliruth/gollum/extensions/dbm_dashboard_EXT/bin/dashboard.js:178:22
    at Layer.handle [as handle_request] (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:137:13)
    at Dashboard.checkAuthOwner (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT.js:316:6)
    at Layer.handle [as handle_request] (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
    at /home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/index.js:281:22
    at param (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/index.js:354:14)
    at param (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/index.js:410:3)
    at next (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at /home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/passport/lib/strategies/session.js:69:12
    at pass (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/passport/lib/authenticator.js:337:31)
    at deserialized (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/passport/lib/authenticator.js:349:7)
    at /home/thaliruth/gollum/extensions/dbm_dashboard_EXT/bin/express.js:40:9
    at pass (/home/thaliruth/gollum/extensions/dbm_dashboard_EXT/node_modules/passport/lib/authenticator.js:357:9)
(node:23859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:23859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by master3395** [comment]
I get the same error.

`
1|nt2  | events.js:288
1|nt2  |       throw er; // Unhandled 'error' event
1|nt2  |       ^
1|nt2  | Error: listen EADDRINUSE: address already in use :::3001
1|nt2  |     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
1|nt2  |     at listenInCluster (net.js:1357:12)
1|nt2  |     at Server.listen (net.js:1445:7)
1|nt2  |     at Function.listen (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/application.js:618:24)
1|nt2  |     at module.exports (/var/www/html/nt2/extensions/dbm_dashboard_EXT/bin/express.js:89:19)
1|nt2  |     at Object.DBM.Bot.onReady (/var/www/html/nt2/extensions/dbm_dashboard_EXT.js:290:47)
1|nt2  |     at Client.emit (events.js:323:22)
1|nt2  |     at WebSocketConnection.triggerReady (/var/www/html/nt2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)
1|nt2  |     at WebSocketConnection.checkIfReady (/var/www/html/nt2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)
1|nt2  |     at GuildCreateHandler.handle (/var/www/html/nt2/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
1|nt2  | Emitted 'error' event on Server instance at:
1|nt2  |     at emitErrorNT (net.js:1336:8)
1|nt2  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
1|nt2  |   code: 'EADDRINUSE',
1|nt2  |   errno: 'EADDRINUSE',
1|nt2  |   syscall: 'listen',
1|nt2  |   address: '::',
1|nt2  |   port: 3001
1|nt2  | }
1|nt2  | (node:4296) UnhandledPromiseRejectionWarning: Error: Command failed: node bot.js
1|nt2  | events.js:288
1|nt2  |       throw er; // Unhandled 'error' event
1|nt2  |       ^
1|nt2  | Error: listen EADDRINUSE: address already in use :::3001
1|nt2  |     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
1|nt2  |     at listenInCluster (net.js:1357:12)
1|nt2  |     at Server.listen (net.js:1445:7)
1|nt2  |     at Function.listen (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/application.js:618:24)
1|nt2  |     at module.exports (/var/www/html/nt2/extensions/dbm_dashboard_EXT/bin/express.js:89:19)
1|nt2  |     at Object.DBM.Bot.onReady (/var/www/html/nt2/extensions/dbm_dashboard_EXT.js:290:47)
1|nt2  |     at Client.emit (events.js:323:22)
1|nt2  |     at WebSocketConnection.triggerReady (/var/www/html/nt2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)
1|nt2  |     at WebSocketConnection.checkIfReady (/var/www/html/nt2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)
1|nt2  |     at GuildCreateHandler.handle (/var/www/html/nt2/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
1|nt2  | Emitted 'error' event on Server instance at:
1|nt2  |     at emitErrorNT (net.js:1336:8)
1|nt2  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
1|nt2  |   code: 'EADDRINUSE',
1|nt2  |   errno: 'EADDRINUSE',
1|nt2  |   syscall: 'listen',
1|nt2  |   address: '::',
1|nt2  |   port: 3001
1|nt2  | }
1|nt2  |     at checkExecSyncError (child_process.js:630:11)
1|nt2  |     at Object.execSync (child_process.js:666:15)
1|nt2  |     at Object.run (/var/www/html/nt2/extensions/dbm_dashboard_EXT/actions/actions/restart_bot_mod.js:108:15)
1|nt2  |     at /var/www/html/nt2/extensions/dbm_dashboard_EXT/bin/dashboard.js:178:22
1|nt2  |     at Layer.handle [as handle_request] (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
1|nt2  |     at next (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:137:13)
1|nt2  |     at Dashboard.checkAuthOwner (/var/www/html/nt2/extensions/dbm_dashboard_EXT.js:316:6)
1|nt2  |     at Layer.handle [as handle_request] (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
1|nt2  |     at next (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:137:13)
1|nt2  |     at Route.dispatch (/var/www/html/nt2/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:112:3)
1|nt2  | (node:4296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
`

**Comment by manugd14** [comment]
Me too
