### ISSUE TITLE
`Error: Cannot find module '../config.json.js.js'

### ISSUE THREAD

**Issue by Ryckie** [greatplainsmodding/DBM-Dashboard#19]
I have followed the install instructions carefully, but am getting this error when I try saving my page text in the admin panel.:
`Error: Cannot find module '../config.json.js.js'
Require stack:
- /home/container/extensions/dbm_dashboard_EXT/bin/dashboard.js
- /home/container/extensions/dbm_dashboard_EXT.js
- /home/container/bot.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
at Function.Module._load (internal/modules/cjs/loader.js:864:27)
at Module.require (internal/modules/cjs/loader.js:1044:19)
at require (internal/modules/cjs/helpers.js:77:18)
at /home/container/extensions/dbm_dashboard_EXT/bin/dashboard.js:214:26
at Layer.handle [as handle_request] (/home/container/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
at next (/home/container/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:137:13)
at Dashboard.checkAuthOwner (/home/container/extensions/dbm_dashboard_EXT.js:316:6)
at Layer.handle [as handle_request] (/home/container/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)
at next (/home/container/extensions/dbm_dashboard_EXT/node_modules/express/lib/router/route.js:137:13)
container:~/
$
`

**Comment by Ryckie** [comment]
I found in what file this error was located, and by removing the .js.js it was fixed.
File is located at extensions\dbm_dashboard_EXT\bin
named: dashboard.js
line: 214
Changed `let config = require('../config.json.js.js');` --> `let config = require('../config.json');`.
