### ISSUE TITLE
Admin Dashboard Problem

### ISSUE THREAD

**Issue by DETLIXX** [greatplainsmodding/DBM-Dashboard#23]
When i try enter Admin Panel, or try choose server. It will give me this error :

TypeError: client.guilds.get is not a function
    at C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\bin\dashboard.js:17:38
    at Layer.handle [as handle_request] (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\route.js:137:13)
    at Dashboard.checkAuth (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT.js:323:12)
    at Layer.handle [as handle_request] (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\matus\OneDrive\Počítač\Active Bots\LuckyGuard\extensions\dbm_dashboard_EXT\node_modules\express\lib\router\index.js:354:14)

**Comment by jnthnz** [comment]
Errors because this hasn't been updated for Discord.JS 12... only thing to do is wait for the dev to update or make ur own one.

**Comment by greatplainsmodding** [comment]
It was updated to work with v12. You can download it from the DBM Networks Github.

**Comment by jnthnz** [comment]
@greatplainsmodding I get this error with your new dashboard

(node:252420) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requireModule' of undefined
    at Object.mod (/DiscordBots/hamster/extensions/dashboard_EXT.js:250:43)
    at Object.<anonymous> (/DiscordBots/hamster/bot.js:368:14)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/DiscordBots/hamster/bot.js:360:23)
    at Array.forEach (<anonymous>)
    at Object.Actions.initMods (/DiscordBots/hamster/bot.js:359:24)
    at Object.Files.startBot (/DiscordBots/hamster/bot.js:1150:11)
    at Object.<anonymous> (/DiscordBots/hamster/bot.js:1848:7)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
(node:252420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:252420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DETLIXX** [comment]
Same problem jnthnz

**Comment by ThykeAdams** [comment]
install aaa_extension_helper

**Comment by jnthnz** [comment]
> install aaa_extension_helper
> 

Appreciate it @ThykeAdams

**Comment by jnthnz** [comment]
@ThykeAdams @greatplainsmodding 

TypeError: /DiscordBots/hamster/extensions/dashboard_EXT/actions/routes/home_page/index.ejs:45
    43|         <div class="container text-center darkBackground features">
    44|             <div class="row text-center">
 >> 45|                 <% for (i = 0; i < data.features.length; i++) {
    46|                     if (i % 2 == 1) { %>
    47|                         
    48|                         <div class="col-md-6 d-none d-lg-block"></div>

Cannot read property 'length' of undefined
    at eval (/DiscordBots/hamster/extensions/dashboard_EXT/actions/routes/home_page/index.ejs:44:38)
    at index (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/ejs/lib/ejs.js:691:17)
    at tryHandleCache (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/express/lib/view.js:135:8)
    at tryRender (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/express/lib/application.js:640:10)
    at Function.render (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/express/lib/response.js:1012:7)
    at /DiscordBots/hamster/extensions/dashboard_EXT.js:438:37
    at Layer.handle [as handle_request] (/DiscordBots/hamster/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/express/lib/router/layer.js:95:5)

**Comment by jnthnz** [comment]
@greatplainsmodding Any help? U saw my message on Discord, I'd at least like an acknowledgement... if its a bug just lmk and ill wait patiently for a fix.

**Comment by greatplainsmodding** [comment]
Seems your config file is
outdated. Are you using the latest version for the config file?

**Comment by jnthnz** [comment]
> Seems your config file is
> outdated. Are you using the latest version for the config file?

If ur talking about DBM Mods, then yes. If not, idk what ur talking about lol sorry

**Comment by krmkcbs** [comment]
i have the same problem.
Cannot read property 'length' of undefined
how i can fix it?

**Comment by greatplainsmodding** [comment]
fixed ;)
