### ISSUE TITLE
Error in "/" Path

### ISSUE THREAD

**Issue by NewtTheWolf** [greatplainsmodding/DBM-Dashboard#27]
TypeError: C:\Users\Newt\Desktop\Alpha Wolf\extensions\dashboard_EXT\actions\routes\home_page\index.ejs:45
    43|         <div class="container text-center darkBackground features">

    44|             <div class="row text-center">

 >> 45|                 <% for (i = 0; i < data.features.length; i++) {

    46|                     if (i % 2 == 1) { %>

    47|                         

    48|                         <div class="col-md-6 d-none d-lg-block"></div>

Cannot read property 'length' of undefined
    at eval (eval at compile (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:661:12), <anonymous>:46:38)
    at index (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:691:17)
    at tryHandleCache (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:272:36)
    at View.exports.renderFile [as engine] (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\response.js:1012:7)
    at C:\Users\Newt\Desktop\Alpha Wolf\extensions\dashboard_EXT.js:287:21
    at Layer.handle [as handle_request] (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\router\layer.js:95:5)

**Comment by NewtTheWolf** [comment]
```
> 
> 
> TypeError: C:\Users\Newt\Desktop\Alpha Wolf\extensions\dashboard_EXT\actions\routes\home_page\index.ejs:45
> 43|
> 
> ```
> 44|             <div class="row text-center">
> ```
> 
> > > 45|                 <% for (i = 0; i < data.features.length; i++) {
> 
> ```
> 46|                     if (i % 2 == 1) { %>
> 
> 47|                         <!-- odd number -->
> 
> 48|                         <div class="col-md-6 d-none d-lg-block"></div>
> ```
> 
> Cannot read property 'length' of undefined
> at eval (eval at compile (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:661:12), :46:38)
> at index (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:691:17)
> at tryHandleCache (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:272:36)
> at View.exports.renderFile [as engine] (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\ejs\lib\ejs.js:489:10)
> at View.render (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\view.js:135:8)
> at tryRender (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\application.js:640:10)
> at Function.render (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\application.js:592:3)
> at ServerResponse.render (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\response.js:1012:7)
> at C:\Users\Newt\Desktop\Alpha Wolf\extensions\dashboard_EXT.js:287:21
> at Layer.handle [as handle_request] (C:\Users\Newt\Desktop\Alpha Wolf\extensions\aaa_extensionHelper_EXT\dashboard_EXT\node_modules\express\lib\router\layer.js:95:5)

```

**Comment by greatplainsmodding** [comment]
fixed ;)
