### ISSUE TITLE
Bot starts but not dashboard when using Glitch

### ISSUE THREAD

**Issue by xkyrux** [greatplainsmodding/DBM-Dashboard#3]
When isGlitch = true the bot starts but I get this error for the dashboard. When I set it to false, the dashboard works fine...

`E:\Bot Projects\Classy Bot>node bot.js
E:\Bot Projects\Classy Bot\extensions\dbm_dashboard_EXT\bin\express.js:9
        Strategy = Dashboard.requireModule('passport-discord').Strategy,
                                                              ^

TypeError: Cannot read property 'Strategy' of undefined
    at module.exports (E:\Bot Projects\Classy Bot\extensions\dbm_dashboard_EXT\bin\express.js:9:63)
    at Object.DBM.Bot.onReady (E:\Bot Projects\Classy Bot\extensions\dbm_dashboard_EXT.js:290:47)
    at Client.emit (events.js:333:22)
    at WebSocketConnection.triggerReady (E:\Bot Projects\Classy Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:128:17)
    at WebSocketConnection.checkIfReady (E:\Bot Projects\Classy Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:144:61)
    at GuildCreateHandler.handle (E:\Bot Projects\Classy Bot\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (E:\Bot Projects\Classy Bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (E:\Bot Projects\Classy Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (E:\Bot Projects\Classy Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (E:\Bot Projects\Classy Bot\node_modules\ws\lib\event-target.js:120:16)`

**Comment by greatplainsmodding** [comment]
Do you host your bot on glitch?

**Comment by greatplainsmodding** [comment]
This is due to not all of the modules being installed. Please make sure the following modules are inside of your package.json file.

```
    "body-parser": "^1.19.0",
    "chalk": "^3.0.0",
    "figlet": "^1.2.4",
    "cookie-parser": "^1.4.4",
    "ejs": "^3.0.1",
    "express": "^4.17.1",
    "express-session": "^1.17.0",
    "fs": "0.0.1-security",
    "passport": "^0.4.1",
    "passport-discord": "^0.1.3",
    "path": "^0.12.7"
```

**Comment by xkyrux** [comment]
I have placed those in package.js already

**Comment by greatplainsmodding** [comment]
can you verify that `"passport-discord": "^0.1.3"` is in the package.json file?

**Comment by greatplainsmodding** [comment]
I haven't tested this on glitch but when I replicated your issue (not having the passport-discord module) I got the same error. I then installed it and it worked.

**Comment by xkyrux** [comment]
I can confirm it is there, but when I open the project in another window, all I get is a blank page with the text "ok"

**Comment by greatplainsmodding** [comment]
Can you send a screenshot, please?

**Comment by greatplainsmodding** [comment]
Also please contact me on discord @Great Plains Modding#4212.

**Comment by xkyrux** [comment]
Alright I have sent you a friend request

**Comment by LGN-Silv** [comment]
I have the same problem

**Comment by greatplainsmodding** [comment]
This is due to not all of the modules being installed. Please make sure the following modules are inside of your package.json file.

```
    "body-parser": "^1.19.0",
    "chalk": "^3.0.0",
    "figlet": "^1.2.4",
    "cookie-parser": "^1.4.4",
    "ejs": "^3.0.1",
    "express": "^4.17.1",
    "express-session": "^1.17.0",
    "fs": "0.0.1-security",
    "passport": "^0.4.1",
    "passport-discord": "^0.1.3",
    "path": "^0.12.7"
```

**Comment by LGN-Silv** [comment]
Okay Thanks.

**Comment by LGN-Silv** [comment]
It's still the same issue.
$ node bot.js
DBM MODS (Node Module Installer v2.5) Attempting To Install Node Module: 'valid-url'. Please wait...

+ valid-url@1.0.9
added 48 packages from 58 contributors, moved 35 packages and audited 395 packages in 4.455s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
DBM MODS (Node Module Installer v2.5) Node Module 'valid-url' has been Installed. You MAY need to restart your bot if theres errors.
/app/extensions/dbm_dashboard_EXT/bin/express.js:9
        Strategy = Dashboard.requireModule('passport-discord').Strategy,
                                                              ^

TypeError: Cannot read property 'Strategy' of undefined
    at module.exports (/app/extensions/dbm_dashboard_EXT/bin/express.js:9:63)
    at Object.DBM.Bot.onReady (/app/extensions/dbm_dashboard_EXT.js:290:47)
    at Client.emit (events.js:194:15)
    at WebSocketConnection.triggerReady (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)
    at WebSocketConnection.checkIfReady (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)
    at GuildCreateHandler.handle (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/rbd/pnpm-volume/7cc060b4-3b6d-4fa2-994e-58b79ced77b1/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
