### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requireModule' of undefined

### ISSUE THREAD

**Issue by FoxXxHater** [greatplainsmodding/DBM-Dashboard#34]
I have this error:

(node:15880) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requireModule' of undefined
    at Object.mod (D:\Discord-Bots\foxco-test\extensions\dashboard_EXT.js:250:43)
    at Object.<anonymous> (D:\Discord-Bots\foxco-test\bot.js:368:14)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Discord-Bots\foxco-test\bot.js:360:23)
    at Array.forEach (<anonymous>)
    at Object.Actions.initMods (D:\Discord-Bots\foxco-test\bot.js:359:24)
    at Object.Files.startBot (D:\Discord-Bots\foxco-test\bot.js:1150:11)
    at Object.<anonymous> (D:\Discord-Bots\foxco-test\bot.js:1848:7)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:15880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Werfamily16** [comment]
I have the same error. Thank you for creating the app though. I loved it when it was working. I wonder how other bots make it looks so easy.

**Comment by TheExplodingGiraffe** [comment]
I also got this error.

**Comment by junesties** [comment]
My error is similar:
node bot.js
(node:9384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requireModule' of undefined
    at Object.mod (G:\Productive\Discord Bots\New Bot Project\extensions\dashboard_EXT.js:250:43)
    at Object.<anonymous> (G:\Productive\Discord Bots\New Bot Project\bot.js:368:14)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (G:\Productive\Discord Bots\New Bot Project\bot.js:360:23)
    at Array.forEach (<anonymous>)
    at Object.Actions.initMods (G:\Productive\Discord Bots\New Bot Project\bot.js:359:24)
    at Object.Files.startBot (G:\Productive\Discord Bots\New Bot Project\bot.js:1150:11)
    at Object.<anonymous> (G:\Productive\Discord Bots\New Bot Project\bot.js:1848:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

(node:9384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


II hope the dev will have a look into it asap...

**Comment by ThomasSova** [comment]
@junesties I'm getting that same error.

**Comment by Winside-Dev** [comment]
Same
