### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by limpens06** [greatplainsmodding/DBM-Dashboard#35]
(node:7344) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\Users\victo\Desktop\Vigon - Development\dashboard\extensions\dashboard_EXT\actions\mods'
    at Object.readdirSync (fs.js:955:3)
    at Object.Dashboard.loadMods (C:\Users\victo\Desktop\Vigon - Development\dashboard\extensions\dashboard_EXT.js:391:21)
    at Object.DBM.Bot.onReady (C:\Users\victo\Desktop\Vigon - Development\dashboard\extensions\dashboard_EXT.js:622:17)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\victo\Desktop\Vigon - Development\dashboard\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\victo\Desktop\Vigon - Development\dashboard\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\victo\Desktop\Vigon - Development\dashboard\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\victo\Desktop\Vigon - Development\dashboard\node_modules\discord.js\src\client\websocket\WebSocketShard.js:467:12)
    at WebSocketShard.onPacket (C:\Users\victo\Desktop\Vigon - Development\dashboard\node_modules\discord.js\src\client\websocket\WebSocketShard.js:439:16)
(node:7344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tyger796** [comment]
create a folder in "C:\Users\victo\Desktop\Vigon - Development\dashboard\extensions\dashboard_EXT\actions" called "mods"
